project:
  type: website
  output-dir: docs

website:
  title: "Closeread Functionalities"
  site-url: https://factorialmap.github.io/scrollytelling_closeread
  navbar:
    left:
      - python_closeread.qmd


format:
  html:
    theme: style.scss
