project:
  type: website
  output-dir: docs  

website:
  title: "scrollytelling_closeread"
  site-url: https://factorialmap.github.io/scrollytelling_closeread
  navbar:
    left:
      - href: index.qmd
        text: Home
      - python_closeread.qmd

format:
  html:
    theme:
      - style.scss
      - _extensions/qmd-lab/closeread/closeread.css
