project:
  type: website
  output-dir: docs

website:
  title: "Scrollytelling Closeread"
  site-url: https://factorialmap.github.io/scrollytelling_closeread
  navbar:
    left:
      - text: "Files"
        menu:
          - text: "Funcionalidades"
            href: python_closeread.html
          - text: "Análise Fatorial Exploratória"
            href: efa.html
          - text: "Controle de Processos"
            href: process_control.html   

format:
  html:
    theme: new.css
