project:
  type: website
  output-dir: docs

website:
  title: "Scrollytelling - Closeread"
  site-url: https://factorialmap.github.io/scrollytelling_closeread
  navbar:
    left:
      - text: "Análises"
        menu:
          - text: "Funcionalidades do Closeread"
            href: python_closeread.html
          - text: "Análise Fatorial Exploratória"
            href: efa.html


format:
  html:
    theme: new.css
